"""Blighted Veil Raid — 🧩 Duo Gear (Stife · Dyth · Meath · Mife · Feath) (from the Gear Setups tab)."""

GEAR = {'order': 5,
 'title': '🧩 Duo Gear (Stife · Dyth · Meath · Mife · Feath)',
 'intro': 'Additional duo gear suggestions. Stife and Dyth are the Strategy '
          '2 Ele pair. **Stats rows are the minimum you need.**',
 'builds': {'stife': {'label': 'Stife',
                      'link': 'https://www.wizbuilder.net/#v4:c:14CY2teXPcng22KxvEj44BFv9HX7VUmj2Jcq6ZayJwn88peXYoKpPCjD9bWK2vFfTykrsGLgUrFzau6XGn7kHVreA2aBXRDZnR4UNMzwTjrp4w69BPLLwRpwR6ets7kwjmxXhWkh5hULvN3DER4cJ2CJa2PHhfiQU627SA29dc3kVQ78sJrQeiDpXj9wxTNQZw7LXVZMgzaTMjqyeQZKv3cb',
                      'slots': [['Hat',
                                 'Crimefighter',
                                 'Life Resist • 2x 180 Life Punishing'],
                                ['Robe',
                                 'Fitzhume',
                                 'Life Acc • 2x 180 Life Punishing'],
                                ['Boots',
                                 'Abomination',
                                 'Life Acc • 2x 180 Life Punishing'],
                                ['Wand',
                                 'Scholomari/Malistaire',
                                 '15% Storm Acc'],
                                ['Athame',
                                 'Abomination',
                                 '145+ HP • 2x Flood Pierce • HP'],
                                ['Amulet', 'Life Omen/Darkmoor', '2x HP'],
                                ['Ring',
                                 'Abomination',
                                 '145+ HP • Storm Damage • HP'],
                                ['Deck', 'Fitzhume', 'HP'],
                                ['Mount', None, None],
                                ['Pet',
                                 'Any Body',
                                 'Storm-Dealer, Storm-Giver, Pain-Giver, '
                                 'Breaker, Piercer, Reinforce']],
                      'min_stats': '11k HP+ • 180 Storm DMG • 340 Life DMG • '
                                   '30 Storm Acc • 10 life Acc • 21 Storm '
                                   'Pierce • 40 Life Pierce • 1 Piece Shad'},
            'dyth': {'label': 'Dyth',
                     'link': 'https://www.wizbuilder.net/builds/mLqopPDAdVSw',
                     'slots': [['Hat',
                                'Scholomari/Malistaire',
                                'Myth Acc • 2x 180 Myth Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Myth Acc • 2x 180 Myth Punishing'],
                               ['Boots',
                                'Crimefighter',
                                'Myth Acc • 2x 180 Myth Punishing'],
                               ['Wand', 'Attunement Rod', '145+ HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Death Damage • HP'],
                               ['Amulet', 'Myth Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Abomination',
                                '145+ HP • Myth Damage • HP'],
                               ['Deck', 'Any Triangle', 'IC Time of Legend'],
                               ['Mount', None, None],
                               ['Pet',
                                'Any Body',
                                'Pain-Giver, Proof, Defy, Any 3x']],
                     'min_stats': '13k+ HP • 216 Death DMG • 190 Myth DMG • '
                                  '15 Death Acc • 20 Myth Acc • 31 Death '
                                  'Pierce • 31 Myth Pierce • 1 Piece Shad'},
            'meath': {'label': 'Meath',
                      'link': 'https://www.wizbuilder.net/builds/qWYae4VrzHLf',
                      'slots': [['Hat',
                                 'Scholomari/Malistaire',
                                 'Death Acc • 2x 180 Death Punishing'],
                                ['Robe',
                                 'Fitzhume',
                                 'Death Acc • 2x 180 Death Punishing'],
                                ['Boots',
                                 'Abomination',
                                 'Death Acc • 2x 180 Death Punishing'],
                                ['Wand', 'Attunement Rod', '145+ HP'],
                                ['Athame',
                                 'Abomination',
                                 '145+ HP • 2x Myth Damage • HP'],
                                ['Amulet', 'Death Omen/Darkmoor', '2x HP'],
                                ['Ring',
                                 'Abomination',
                                 '145+ HP • Myth Damage • HP'],
                                ['Deck', 'Fitzhume/Monster Hide', 'HP'],
                                ['Mount', None, None],
                                ['Pet',
                                 'Any Body',
                                 'Pain-Giver, Proof, Defy, Any 3x']],
                      'min_stats': '13k+ HP • 216 Death DMG • 215 Myth DMG • '
                                   '15 Death Acc • 20 Myth Acc • 38 Death '
                                   'Pierce • 31 Myth Pierce • 3 Piece Shad'},
            'mife': {'label': 'Mife',
                     'link': 'https://www.wizbuilder.net/#v4:c:14CY2tgvy5qM8J5fsn7QGNayh5yYoq52mvsw1pcUyKFvAxfv3GqFzYsB7L15vdtZbovPdFPtz2FqAjoMuoNWJmaWTekAFstETmX716wxh6NFnAjMNXwK9fmZNMPUrgFtYGYceM2GXxRsUjaheAxSC7cNaAqkBURf3R5fnXwsm9bnoUqWxA9D7Cd9pbjTNJFDKz2oNrdjN9gTayVgxQ4DtKaf',
                     'slots': [['Hat',
                                'Monster Hide',
                                'Ice Resist • 2x 180 Life Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Life Acc • 2x 180 Life Punishing'],
                               ['Boots',
                                'Abomination',
                                'Life Acc • 2x 180 Life Punishing'],
                               ['Wand', 'Monster Hide', 'Any'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Myth Damage • HP'],
                               ['Amulet', 'Life Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Abomination',
                                '145+ HP • Myth Damage • HP'],
                               ['Deck', 'Monster Hide', 'HP'],
                               ['Mount', None, None],
                               ['Pet', 'Any Body', 'Proof, Defy, 4x Any']],
                     'min_stats': '13.5k HP • 190 Myth DMG • 190 Life DMG • '
                                  '20 Myth Acc • 10 Life Acc • 30 Myth '
                                  'Pierce • 30 Life Pierce'},
            'feath': {'label': 'Feath',
                      'link': 'https://www.wizbuilder.net/#v4:c:1NUCq9YG1g8UdSQZ3Z4U8hRP41i57eut4SdkAcTaQa8HzhQep4FPKPEyvgf2QfhjWmu8ktWUUnMUfjKt8W3JGpuTPDjXuxpkC9JQJPMWG5woHfMGgx4Zwpp3sYWci3ZixqtkZgemsA5ZDRMDPnxhja1ixCWsg3e9pe3k3BWmZjq3kDBZvVNvvsWDBHRbLZTTQVnDfFzoEKVrTY9bzmiwFmgYkUebH',
                      'slots': [['Hat',
                                 'Scholomari/Malistaire',
                                 'Death Acc • 2x 180 Death Punishing'],
                                ['Robe',
                                 'Barkingham/Takanobu',
                                 'Death Acc • 2x 180 Death Punishing'],
                                ['Boots',
                                 'Abomination',
                                 'Death Acc • 2x 180 Death Punishing'],
                                ['Wand', 'Fitzhume', 'HP'],
                                ['Athame',
                                 'Abomination',
                                 '145+ HP • 2x Ember Pierce • HP'],
                                ['Amulet', 'Death Omen/Darkmoor', '2x HP'],
                                ['Ring',
                                 'Abomination',
                                 '145+ HP • Ember Pierce • HP'],
                                ['Deck', 'Monster Hide', 'HP'],
                                ['Mount', None, None],
                                ['Pet',
                                 'Any Body / Happy Jackal',
                                 'Fire-Dealer, Fire-Giver, Pain-Giver, '
                                 'Breaker, Piercer, Any']],
                      'min_stats': '13k HP+ • 195 Fire DMG • 245 Death DMG • '
                                   '25 Fire Acc • 15 Death Acc • 60 Fire '
                                   'Pierce • 50 Death Pierce • 1 Piece '
                                   'Shad'}}}
