"""Blighted Veil Raid — 🔵 -ice Gear (from the Gear Setups tab)."""

GEAR = {'order': 1,
 'title': '🔵 -ice Gear',
 'intro': '-ice can be any Ice build — pick the one that matches your '
          'school. **Stats rows are the minimum you need.**',
 'builds': {'ice': {'label': 'Ice',
                    'link': 'https://www.wizbuilder.net/builds/AYkCmLldKfzM',
                    'slots': [['Hat', 'Abomination', 'Death Resist'],
                              ['Robe', 'Monster Hide', None],
                              ['Boots', 'Malistaire', None],
                              ['Wand', 'Fitzhume', 'HP'],
                              ['Athame',
                               'Abomination',
                               '145+ HP • 2x Ice Pierce • HP'],
                              ['Amulet',
                               'Imperial Court Ampul',
                               'Ice Pierce • IC Darkwind'],
                              ['Ring',
                               'Abomination',
                               '145+ HP • Ice Pierce • HP'],
                              ['Deck', 'Any Circle', 'Ice DMG'],
                              ['Mount', None, None],
                              ['Pet',
                               'Any Body',
                               'Ice-Dealer, Ice-Giver, Pain-Giver, Proof, '
                               'Mighty, Defy']],
                    'min_stats': 'High HP • 193 Ice DMG • 50 Res • 20 Ice '
                                 'Acc • 43 Ice Pierce • 2 Piece Shad'},
            'fice': {'label': 'Fice',
                     'link': 'https://www.wizbuilder.net/#v3:19cESKXyqrcX6MrvTiQm3Eeb92B9oUrKvnaefGzatwBwQj83M7mZwGvu16euRmsQ41iX1MdAzBXv4AtRhzKW5QzRYj4CBZTA8rract6wgDMTtQr2n1ZpRwCWBnJFS5pxKwn1jM9Shb9cPbfs1T7dzZ5Jc8JBPx7fLtg1jdDe5iDM',
                     'slots': [['Hat',
                                'Monster Hide',
                                'Myth Resist • 2x 180 Ice Punishing'],
                               ['Robe',
                                'Monster Hide',
                                '2x Ice Acc • 180 Ice Punishing'],
                               ['Boots',
                                'Abomination',
                                'Ice Acc • 2x 180 Ice Punishing'],
                               ['Wand', 'Monster Hide', 'HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Ice Pierce • HP'],
                               ['Amulet', 'Ice Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Mali/Nothing 180',
                                '145+ HP • HP • Ice Acc',
                                'Ring options: Wastelander / Scholomari / '
                                'Malistaire.'],
                               ['Deck', 'Any Triangle', 'IC Darkwind'],
                               ['Mount', None, None],
                               ['Pet', 'Any Body', 'Proof, Defy, Any 4x']],
                     'min_stats': 'High HP • 193 Ice DMG • 50 Res • 20 Ice '
                                  'Acc • 43 Ice Pierce • 2 Piece Shad'},
            'bice': {'label': 'Bice',
                     'link': 'https://www.wizbuilder.net/#v2:N4IgbiBcCMA0IBsrQBwAZ4GcogEIEMF8A7AYwFMR5ioBtPAQQBkGA5AYQFEqR2B5AMoAVAKoBZbgF14AcyigAEvgAuOAEYBXAJYIAJuQBOMAOxpjANmPQeAJQD2aypBCad+o9GMAmAMx+fPLh2dsrYzq56hiZm5uYALDwA6iS66tqRHqYWAJzZPAzKABb4ALZOLunu0cam5vklGgjkquGVUdA+FnE+CfA2WsRyrW7tVl4ouTwAIuSkANZpIx4ArJ3mnjxidhrELcSNCPAACs1Q+wgIAL7wAFbyIEotoJiFWuR6APpoixkwyyjGHzLPJYADudgMug+1mGv08aGWxmWXh4mHBkI+KNhVXhiORIGuIHsjnuaIhUO+2NGCKRKLB5MxPxxpjxdJAAAc7KDDNCme1-oDltZCUEQmFnuiKXzMjT8fBOdyDLyqSsAUDrPSMViKktoqyCfBksRUpBngBHDT4AzkD4IOzzchSlV6qwBQkFYple7KchW232uaOr7Sv5Ayx1eCkLQGUhNf0OqEwnVwoFeGoBSPR2M2u0JxnOjrI9Ooi1WnMBoMBAss10GkAMBpNJ4gTCl63xwNO5PMmkdEuW9u5zvK7vUxF9wn9Qbe31KodBymjlZhiz9ssdoNJiI98cZkDKAxaEgyOPzqHa7f88bLf51mbzb2H4+nitdy8eIEodbCwnsuheG9YAAjAvHMECwKA5Y0Gkfc6BAI58AGABaABxLQwEMHgAEkKFQ9DMPgHDyCQmZCAIkAxC0GRCmUABPHgBHZd4ECQo4DGCAAzBimIuEjyA42iBjkGDSCgDAQHwMTLiAA',
                     'slots': [['Hat',
                                'Monster Hide',
                                'Life Resist • 2x 180 Ice Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Ice Acc • 2x 180 Ice Punishing'],
                               ['Boots',
                                'Abomination',
                                'Ice Acc • 2x 180 Ice Punishing'],
                               ['Wand', 'Monster Hide', 'HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Ice Pierce • HP'],
                               ['Amulet', 'Ice Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Mali/Nothing 180',
                                '145+ HP • HP • Ice Acc',
                                'Ring options: Wastelander / Scholomari / '
                                'Malistaire.'],
                               ['Deck', 'Any Triangle', 'IC Darkwind'],
                               ['Mount', None, None],
                               ['Pet',
                                'Any Body',
                                'Ice-Dealer, Ice-Giver, Pain-Giver, Proof, '
                                'Mighty, Defy']],
                     'min_stats': 'High HP • 193 Ice DMG • 50 Res • 20 Ice '
                                  'Acc • 43 Ice Pierce • 2 Piece Shad'},
            'lice': {'label': 'Lice',
                     'link': 'https://www.wizbuilder.net/#v4:c:1NUCq9p7LQv4SpzurFZcBQnsHuUoarhQsTkFcJpXkWss3LhANHWNCP5wGq4JcvyyGLe2Rv5AiAbaai41v2BtBE3aCnwmydHAEchSCo9TLNyvYcpedpHTTMZW1WHfNsgkkSNZoT8H4Q6gfwNQ43xcTHKMrhYpnxF52WrjhGBJRXAZwNLrPN26pSpQKQS73dfd7vFLkweq1nK85Muey8MN4dYa6zKyq',
                     'slots': [['Hat',
                                'Fitzhume',
                                'Myth Resist • 2x 180 Ice Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Ice Acc • 2x 180 Ice Punishing'],
                               ['Boots',
                                'Crimefighter',
                                '2x 180 Ice Punishing'],
                               ['Wand', 'Supreme Old Judge Staff', 'HP'],
                               ['Athame',
                                '170-180+ Triangle',
                                '145+ HP • 2x Ice Pierce • Ice Acc'],
                               ['Amulet', 'Ice Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Abomination',
                                '145+ HP • Ice Pierce • HP'],
                               ['Deck', 'Any Triangle', 'IC Darkwind'],
                               ['Mount', None, None],
                               ['Pet',
                                'Any Body',
                                'Ice-Dealer, Giver, Breaker, Proof, Mighty, '
                                'Defy']],
                     'min_stats': 'High HP • 193 Ice DMG • 50 Res • 20 Ice '
                                  'Acc • 43 Ice Pierce • 2 Piece Shad'},
            'mice': {'label': 'Mice',
                     'link': 'https://www.wizbuilder.net/#v2:N4IgbiBcCMA0IBsrQBwAZ4GcogLIE8AXACxHgDsoBtPATQBUAJMkAYQHkBlegVVwFEQAXXgBzKKEYBDQjgBGAVwCWCACYBTAE4wA7ACYAzEegsASgHs56+crVbdhoyhYAhc+cLZIIRSo3boHWhDNAAWFgB1KXJVGz97QLQdHTCWAEESKQBba29fOwCU5OgTeDSshQR1WTzbfxgDHQA2UINw+FMlcnFa+MLggE5U+AARdQBjAGs4gpgAVkamwJZccwVyGvJKhHgABWqoLYQEAF94ACsJEGka0ExiJXU1AH00GfroOZQdNtKQTAA7uZNKpniZerNEl9WixAcDQXp3gkUtCDCAziALFYrgAHcwArRgpEBL4-OZ-OEg17E3RoVGwoFUxEQj4olAwjFuDxeO6M0FvFnIunstHwPEEzREwUk74GckM+HPZk+OpC+kYqIxK6YACOCikmnUzwQ5im6n5NMC0FCKHQ6LKmRyV0I6gNxtNk3N1Ol8zlTWaLHGSk04yq7rNoPBKr6DTmemSopAQZDYZNEaVlrl8Z+sL1BqNac9oLRPqtNrtGPKlQOkDuecN4aL3ujkKC5beWHrBY9Xqj+VZ1ttbwxnW6ztdksLXoFLY+Czm-qauf1DankctbaHLEImiU0VEqZ7CMtcZQcy+9pAYymzt3+8P6Zn-YScpQSxMJwxOOoenPsF-GB6E0gHAf+cxoCIIA1DQLCwfAnA4k8CAALS7Jo7gAGYsAhSHIWMGH4F04jwMI8DjFAGAgFIFEnEAA',
                     'slots': [['Hat',
                                'Fitzhume',
                                'Death Resist • 2x 180 Ice Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Ice Acc • 2x 180 Ice Punishing'],
                               ['Boots',
                                'Crimefighter',
                                '2x 180 Ice Punishing'],
                               ['Wand', 'Monster Hide', 'HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Ice Pierce • HP'],
                               ['Amulet', 'Ice Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Triangle+Square 170+',
                                '145+ HP • HP • Ice Acc',
                                'Ring options: Wastelander / Scholomari / '
                                'Malistaire.'],
                               ['Deck', 'Any Triangle', 'IC Darkwind'],
                               ['Mount', None, None],
                               ['Pet', 'Any Body', 'Proof, Defy, Any 4x']],
                     'min_stats': 'High HP • 193 Ice DMG • 50 Res • 20 Ice '
                                  'Acc • 43 Ice Pierce • 2 Piece Shad'},
            'dice': {'label': 'Dice',
                     'link': 'https://www.wizbuilder.net/#v2:N4IgbiBcCMA0IBsrQBwAZ4GcogCIFMBDAFwAsR4A7KAbTwFEBBAFQAkKQBhAeQGVmAqgFl6IALrwA5lFCsSOAEYBXAJYIAJvgBOMAOxpdANl0AmDgCUA9gvyLVG7XpMBmVwBYOAIUuXi2SCDKapo60PpGhgCsHADqhJTqdsGOYQb6aByMZIQAtrYBQQ6h4eGZOUoI+MRJRTDORm7OHvDmKpTSBfYhetAmAJxoGfAEAMYA1jXd0JH1hmEcQpZKlNWQlBUI8AAKVVDrCAgAvvAAVjIgcqugmKQq+BoA+hmdyaGRKLrOxhyYAO6WWnUD2gkxS+kiun0P3+gIeZhetVSEKhxxAVhs5z+AKBz0CXTBaGRQxAWNh8Lxrz0hMhxIADpZftpgaC3h9nJEQajvL5-NcYTiWVSiRx6YytMyEVN3p8OdDsXDBUiaSBUXEEpiAI5KQhafAPBCWcb4AWSsHQNwfXQq+BZUi5fKgYhEcUGo0mimImaRYyGDgjFRaEaVfWGsbGiUeqbskyQ5x+gNBvWusNA8mFKORGOfH5anVJ0PhuOm4rmy3WkCMcqVK4k3O6kNup6K3SlyE57X15PhkHFnoWtuo1rtc5OnUNlNN3vTdk+9t58fd5utq3wYhaFTxSTBrupxUQlAoaC+1GjCaQR3rzfbgvu9MpdkoOac1G02gmSKRWDvjAmQw-v9fpEaASCAqx0AAkiM+AALQEIQlRaBwkEwQA4ioYDaBwHC8LS9wINBWxaD4ABm2G4QcsH4MRACebTSPA4jwCMUAYCAhAsYcQA',
                     'slots': [['Hat',
                                'Monster Hide',
                                'Life Resist • 2x 180 Ice Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Ice Acc • 2x 180 Ice Punishing'],
                               ['Boots',
                                'Abomination',
                                'Ice Acc • 2x 180 Ice Punishing'],
                               ['Wand', 'Monster Hide', 'HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Ice Pierce • HP'],
                               ['Amulet', 'Ice Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Mali/Nothing 180',
                                '145+ HP • HP • Ice Acc',
                                'Ring options: Wastelander / Scholomari / '
                                'Malistaire.'],
                               ['Deck', 'Any Triangle', 'IC Darkwind'],
                               ['Mount', None, None],
                               ['Pet',
                                'Any Body',
                                'Ice-Dealer, Ice-Giver, Pain-Giver, Proof, '
                                'Defy']],
                     'min_stats': 'High HP • 193 Ice DMG • 50 Res • 20 Ice '
                                  'Acc • 43 Ice Pierce • 2 Piece Shad'}}}
