"""Blighted Veil Raid — 🟢 Lyth/Mife Gear (from the Gear Setups tab)."""

GEAR = {'order': 2,
 'title': '🟢 Lyth/Mife Gear',
 'intro': 'Lyth/Mife plays either Lyth (Life + Myth) or Mife (Myth + Life). '
          '**Stats rows are the minimum you need.**',
 'builds': {'lyth': {'label': 'Lyth',
                     'link': 'https://www.wizbuilder.net/#v3:13wNoPzGAZFvsa2GBLMm1vdVec4DGQQFRyJqhBkGahmhRpnUrtQwhA5H73xecsKwe9kce8AH7wF23iLyEDCTvdcbS6KyFSRcsPAZL4WySSVniUFKsowzbSuNH9yVhL4PFg3nEXVnkN95FJ3WYPYtj3x7GkT1AXgsGEGZ9HxER1jDAWj',
                     'slots': [['Hat',
                                'Scholomari/Malistaire',
                                'Myth Acc • 2x 180 Myth Punishing'],
                               ['Robe',
                                'Crimefighter',
                                '2x Myth Acc • 180 Myth Punishing'],
                               ['Boots',
                                'Abomination',
                                'Myth Acc • 2x 180 Myth Punishing'],
                               ['Wand', 'Attunement Rod', '145+ HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Memory Pierce • HP'],
                               ['Amulet', 'Myth Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Abomination',
                                '145+ HP • Memory Pierce • HP'],
                               ['Deck', 'Any Triangle', 'IC Wyldfire'],
                               ['Mount', None, None],
                               ['Pet',
                                'Gargoyle',
                                'Life-Bringer, Life-Giver, Pain-Giver, '
                                'Breaker, Any 2x']],
                     'min_stats': 'High HP • 192 Life DMG • 130 Myth DMG • '
                                  '10 Life Acc • 20 Myth Acc • 46 Life '
                                  'Pierce • 36 Myth Pierce • 3 Piece Shad'},
            'mife': {'label': 'Mife',
                     'link': 'https://www.wizbuilder.net/#v3:19cESKmUwporLfZXMPuASjg5uF7fSDbSDN8aoCwiTMcLpMVam1r1NmdaBXjtWyEzh7q7fmfLS3qtMz7H1rbPTxhsUPnTaEFAMmLLx3Zvpc8GaCjYAM5kb1iCoodMUfs2PLvuoz5dsTssSvee9BFAAwTS8ELJbo2WQfjyqvxhjULw',
                     'slots': [['Hat',
                                'Monster Hide',
                                'Death Resist • 2x 180 Life Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Life Acc • 2x 180 Life Punishing'],
                               ['Boots',
                                'Malistaire',
                                'Life Acc • 2x 180 Life Punishing'],
                               ['Wand', 'Monster Hide', 'HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Creation Pierce • HP'],
                               ['Amulet', 'Life Omen/Darkmoor', '2x HP'],
                               ['Ring',
                                'Abomination',
                                '145+ HP • Life DMG • HP'],
                               ['Deck',
                                'Any Triangle/Square',
                                'IC Wyldfire / HP'],
                               ['Mount', None, None],
                               ['Pet',
                                'Any/Lord of Summer',
                                'Proof, Defy, Any 4x (Can Ice/Myth/Fire '
                                'Ward)']],
                     'min_stats': 'High HP • 192 Life DMG • 130 Myth DMG • '
                                  '10 Life Acc • 20 Myth Acc • 50 Life '
                                  'Pierce • 36 Myth Pierce • 3 Piece Shad'}}}
