"""Blighted Veil Raid — 🟣 Steath Gear (from the Gear Setups tab)."""

GEAR = {'order': 4,
 'title': '🟣 Steath Gear',
 'intro': 'Two Steath sets — Set 1 uses the Triangle athame with Uni Acc, '
          'Set 2 uses the Abomination athame. **Stats rows are the minimum '
          'you need.**',
 'builds': {'set1': {'label': 'Set 1',
                     'link': 'https://www.wizbuilder.net/#v3:19cESKdP5YCqAxEHv3TUC9rFPFSB5H7kHEk7xBmxN48yaJxUBLnTz1Z8AKxZZVm38kuA3VVZWnpgxf3rMx1zzjNoDFgY5fLmpgsB5STH6dYLWUJzZFXAX7Xe3qTAYqnb8Xx7QM6w49ibxjWvxWaJTyTDxgL3XgfWxuGFGTbjMJWB',
                     'slots': [['Hat',
                                'Scholomari/Malistaire',
                                '2x 180 Death Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Death Acc • 2x 180 Death Punishing'],
                               ['Boots',
                                'Abomination',
                                'Death Acc • 2x 180 Death Punishing'],
                               ['Wand', 'Attunement Rod', '145+ HP'],
                               ['Athame',
                                '170-180+ Triangle',
                                '145+ HP • 2x Typhoon Pierce • Uni Acc'],
                               ['Amulet', 'Darkmoor', '2x HP'],
                               ['Ring',
                                'Abomination',
                                '145+ HP • Typhoon Pierce • HP'],
                               ['Deck',
                                'Abomination/Any Circle',
                                'Storm Damage'],
                               ['Mount', None, None],
                               ['Pet',
                                'Any Body',
                                'Death-Dealer, Death-Giver, Pain-Giver, '
                                'Breaker, Mortis Rage/Any']],
                     'min_stats': '10k HP+ • 206 Storm DMG • 350 Death DMG • '
                                  '30 Storm Acc • 15 Death Acc • 21 Storm '
                                  'Pierce • 50 Death Pierce • 2 Piece Shad'},
            'set2': {'label': 'Set 2',
                     'link': None,
                     'slots': [['Hat',
                                'Scholomari/Malistaire',
                                '2x 180 Death Punishing'],
                               ['Robe',
                                'Fitzhume',
                                'Death Acc • 2x 180 Death Punishing'],
                               ['Boots',
                                'Abomination',
                                'Death Acc • 2x 180 Death Punishing'],
                               ['Wand', 'Attunement Rod', '145+ HP'],
                               ['Athame',
                                'Abomination',
                                '145+ HP • 2x Typhoon Pierce • HP'],
                               ['Amulet', 'Darkmoor', '2x HP'],
                               ['Ring',
                                'Abomination',
                                '145+ HP • Typhoon Pierce • HP'],
                               ['Deck',
                                'Abomination/Any Circle',
                                'Storm Damage'],
                               ['Mount', None, None],
                               ['Pet',
                                'Any Body',
                                'Death-Dealer, Death-Giver, Pain-Giver, '
                                'Breaker, Sharp-Shot, Mortis Rage/Any']],
                     'min_stats': '10k HP+ • 206 Storm DMG • 350 Death DMG • '
                                  '30 Storm Acc • 15 Death Acc • 21 Storm '
                                  'Pierce • 50 Death Pierce • 2 Piece Shad'}}}
