"""Blighted Veil Raid — Strategy 2: -ice · Stire · Stife · Dyth.

Inside-team plan, pulled from the combat guide sheet (Strategy 2 tab).
Row format for the turn tables (same idea as the Ghastly plan tables):

    [turn, player1_action, player2_action]          normal turn
    [turn, player1_action, player2_action, note]    turn with a heads-up note
    [turn, shared_action]                           both players do the same

Import from `plan` (the package re-exports everything), not from here.
"""

STRATEGY_2 = {'key': '2',
 'name': 'Strategy 2',
 'lineup': '-ice · Stire · Stife · Dyth',
 'popular': False,
 'onis_order': ['Storm', 'Myth', 'Fire', 'Death', 'Life', 'Ice'],
 'onis': {'Storm': {'cols': ['-ice', 'Dyth'],
                    'discard': ['giant, dp, surge, darkwind', 'none'],
                    'rows': [['1', 'Pass', 'Frenzy/Reinforce'],
                             ['2', 'Attenuate', 'Wand Hit'],
                             ['3-4',
                              '(TC) Woolly B',
                              'Death Scion 5B',
                              'Wait for Oni to be first before hitting\n'
                              '0.8% chance of 2x crit fail']]},
          'Myth': {'cols': ['Stife', 'Stire'],
                   'discard': ['owl, surge', 'ammut, jinn, king art'],
                   'rows': [['1', 'Pass', 'Pass'],
                            ['2', 'Pass if player first'],
                            ['3', 'TC Earthwalker B', 'Reinforce'],
                            ['4', 'Attenuate', 'TC Storm Shark A'],
                            ['5', 'TC Earthwalker B', 'Fire Scion B']]},
          'Fire': {'cols': ['-ice', 'Stife'],
                   'discard': ['none/grab it from side',
                               'surge, owl, attenuates'],
                   'rows': [['1', 'Donate Power P2', 'Pass'],
                            ['2', 'Attenuate', 'Reinforce'],
                            ['3',
                             '(TC) Donate Power P2',
                             'TC Storm King Art B'],
                            ['4', 'Pass', 'Thundering Jinn']]},
          'Death': {'cols': ['Dyth', 'Stire'],
                    'discard': ['scions, bubble, frenzy, shrike', 'none'],
                    'rows': [['1', 'Attenuate', 'Pass'],
                             ['2', 'TC Vampire A', 'Reinforce'],
                             ['3', 'TC Minotaur B', 'Caldera Jinn'],
                             ['4', 'Wand Hit', 'Pass']]},
          'Life': {'cols': ['Stife', '-ice'],
                   'discard': ['none', 'woolly, attenuate, surge'],
                   'rows': [['1', 'Pass', 'Donate Power Self'],
                            ['2', 'Weave Attenuate', 'IC Darkwind'],
                            ['3', 'Reinforce', '(TC) Frost Giant B'],
                            ['4', 'Storm Owl A', 'Pass']]},
          'Ice': {'cols': ['Stire', 'Dyth'],
                  'discard': ['scion, jinn, king art', 'none'],
                  'rows': [['1', 'Reinforce', 'Attenuate'],
                           ['2', 'TC Phoenix A', 'Frenzy/Reinforce'],
                           ['3', 'Pass', 'Time of Legend'],
                           ['4', 'Ammut B', 'Myth Scion B']]}},
 'roots': {'spirit': {'cols': ['-ice (Pull Myth From Back)',
                               'Stire (Stagger)'],
                      'discard': ['giant, storm/fire scion',
                                  'jinn, ice scion'],
                      'rows': [['1', 'IC Darkwind', 'Reinforce'],
                               ['2',
                                'Donate Power P2',
                                'Weave Attenuate Life'],
                               ['3',
                                'TC Empower / Pass If Freeze Ray',
                                'Storm King Art B Life'],
                               ['4', '(TC) Woolly / Ray Life', 'TC Empower'],
                               ['5',
                                'TC Empower',
                                'Storm Scion B Life (if 4 blades)'],
                               ['6', '(TC) Donate Power P2', 'TC Furnace'],
                               ['7', '(TC) Donate Power P2', 'Ammut B Myth'],
                               ['8', 'Dark Surge P2', 'Shadow Shrike'],
                               ['9',
                                'Attenuate Myth',
                                'Fire Scion B Myth (if 3 dots)'],
                               ['10',
                                'Ice Scion B Death (if 4 shields)',
                                'Fire Scion B Death']],
                      'notes': {'1': 'Click So Fast',
                                '3': 'C: Life in Key',
                                '4': 'C: Death in [Life Root Slot]',
                                '7': 'C: Myth in Sun',
                                '8': 'If shields stop stalling'},
                      'mana': ['25 Mana', '38 Mana']},
           'ele': {'cols': ['Stife (Pull Storm)', 'Dyth'],
                   'discard': ['owl, jinn, death/myth scion',
                               'atten, bubble, wand, myth train/life scions'],
                   'rows': [['1', 'Attenuate Fire', 'TC Empower'],
                            ['2',
                             'TC Donate Power P2',
                             'TC Skeletal Dragon B Storm'],
                            ['3', 'Reinforce', 'Pass'],
                            ['4', 'Life Scion Fire', 'TC Empower'],
                            ['5',
                             'Weave Attenuate Storm',
                             'Death Scion 5B Storm'],
                            ['6', 'Pass', 'TC Empower'],
                            ['7',
                             '(TC) Earth Walker Ice',
                             'TC Basilisk B Ice'],
                            ['8', 'Attenuate Ice', 'Frenzy'],
                            ['9', 'Dark Surge P2', 'Shadow Shrike'],
                            ['10', 'Pass', 'Myth Scion B Ice']],
                   'notes': {'1': 'Stall So Much',
                             '2': 'C: Storm in Key',
                             '5': 'Click So Fast',
                             '7': 'C: Fire in [Ice Root Slot]',
                             '8': 'C: Ice in Key'},
                   'mana': ['14 Mana', '35 Mana']}},
 'decks': {'Ice': {'label': 'Ice (main Ice)',
                   'spells': ['Frost Giant B',
                              'Woolly B',
                              '(IC) Donate Power',
                              'Attenuate',
                              'Dark Surge',
                              'IC Darkwind'],
                   'tc': ['Donate Power',
                          'Donate Power',
                          'Donate Power',
                          'Empower 2x']},
           '-Ice': {'label': '-Ice (off-school Ice)',
                    'spells': ['Donate Power',
                               'Donate Power',
                               '(IC) Donate Power',
                               'Attenuate',
                               'Dark Surge',
                               'IC Darkwind'],
                    'tc': ['Woolly B',
                           'Woolly B',
                           'Frost Giant B',
                           'Empower 2x']},
           'Stire': {'label': 'Stire',
                     'spells': ['Storm King Art B',
                                'Ammut B',
                                'Fire Scion B (can be wc)',
                                'Caldera Jinn',
                                'Reinforce (pet!)',
                                'Weave Attenuate',
                                'Shadow Shrike'],
                     'tc': ['Storm Shark A',
                            'Phoenix A',
                            'Empower',
                            'Furnance']},
           'Stife': {'label': 'Stife',
                     'spells': ['Attenuate',
                                'Attenuate',
                                'Weave Attenuate',
                                'Thundering Jinn',
                                'Storm Owl A',
                                'Dark Surge',
                                'Reinforce',
                                'Earth Walker B (optional)'],
                     'tc': ['Earth Walker B 3x',
                            'Storm King Art B',
                            'Donate Power'],
                     'notes': ['Only need 1 Earth Walker B TC if you use it '
                               'in your main deck.']},
           'Dyth': {'label': 'Dyth',
                    'spells': ['Attenuate',
                               'Frenzy/Reinforce',
                               'Wand Hit',
                               'Myth Scion B (can be wc)',
                               'Death Scion 5B',
                               'Shadow Shrike',
                               'Time of Legend'],
                    'tc': ['Empower 3x',
                           'Basilisk B',
                           'Vampire A',
                           'Minotaur B',
                           'Skeletal Dragon B'],
                    'notes': ['Time of Legend can be trained or an item '
                              'card.']}},
 'deck_notes': [('Woolly B slot',
                 'This can be **Freeze Ray B** — remove 1x Empower TC, and '
                 'pass on Turn 3 in Spirit Roots.'),
                ('Last slot',
                 "You don't need a card here. If you have training points: "
                 '1. Woolly B or Freeze Ray B • 2. Donate Power • 3. Donate '
                 'Power • 4. Donate Power • 5. Attenuate • 6. Dark Surge • '
                 '7. IC Darkwind. TC: 2x Empower (1x if Freeze Ray) + Frost '
                 'Giant B. If Freeze Ray — pass R3 of Roots.'),
                ('Treasure cards',
                 'No need to pack Woolly if you main-deck Freeze Ray B. '
                 'Empower x1 if Freeze Ray.')]}
