"""Blighted Veil Raid — Strategy 1: -ice · Lyth/Mife · Stire · Steath.

Inside-team plan, pulled from the combat guide sheet (Strategy 1 tab).
Row format for the turn tables (same idea as the Ghastly plan tables):

    [turn, player1_action, player2_action]          normal turn
    [turn, player1_action, player2_action, note]    turn with a heads-up note
    [turn, shared_action]                           both players do the same

Import from `plan` (the package re-exports everything), not from here.
"""

STRATEGY_1 = {'key': '1',
 'name': 'Strategy 1',
 'lineup': '-ice · Lyth/Mife · Stire · Steath',
 'popular': True,
 'onis_order': ['Storm', 'Myth', 'Fire', 'Death', 'Life', 'Ice'],
 'onis': {'Storm': {'cols': ['-ice (main ice no discard)', 'Steath'],
                    'discard': ['giant, dp, surge, darkwind', 'none'],
                    'rows': [['1', 'Pass', 'Pass'],
                             ['2',
                              'Attenuate',
                              'Frenzy/Reinforce (WC Death Scion)'],
                             ['3-4',
                              '(TC) Woolly B / Freeze Ray B',
                              'Death Scion B',
                              'Wait for Oni to be first before hitting']]},
          'Myth': {'cols': ['Lyth/Mife', 'Stire'],
                   'discard': ['oni, frenzy, surge', 'none'],
                   'rows': [['1', 'TC/IC Empower / IC Wyldfire', 'Pass'],
                            ['2', 'Attenuate', 'Pass'],
                            ['3', 'IC Wyldfire / TC Empower', 'Reinforce'],
                            ['4', 'The World B', 'Fire Scion B']]},
          'Fire': {'cols': ['Steath', '-ice'],
                   'discard': ['none', 'none/grab it from side'],
                   'rows': [['1', 'Pass', 'Attenuate'],
                            ['2', 'Frenzy/Reinforce', 'Donate Power P1'],
                            ['3', 'Storm King Art B', '(TC) Donate Power P1'],
                            ['4', 'Thundering Jinn', 'Pass']]},
          'Death': {'cols': ['Lyth/Mife', 'Stire'],
                    'discard': ['oni, world, surge, emp, frenzy', 'none'],
                    'rows': [['1', 'Attenuate', 'Pass'],
                             ['2', 'IC Wyldfire', 'Reinforce'],
                             ['3', 'TC Minotaur B', 'Caldera Jinn']]},
          'Life': {'cols': ['Steath', '-ice (main ice no discard)'],
                   'discard': ['none', 'woolly, attenuate, surge'],
                   'rows': [['1', 'Pass', 'Donate Power Self'],
                            ['2', 'Attenuate', 'IC Darkwind'],
                            ['3', 'Frenzy/Reinforce', '(TC) Frost Giant B'],
                            ['4', 'Storm Owl A', 'Pass']]},
          'Ice': {'cols': ['Lyth/Mife', 'Stire'],
                  'discard': ['world, surge, wyldfire, emp',
                              'scion, caldera, attenuate, art, shrike'],
                  'rows': [['1', 'Pass Quick', 'Pass Quick'],
                           ['2', 'Pass Quick', 'Pass Quick'],
                           ['3', 'Frenzy', 'Reinforce'],
                           ['4', 'Attenuate', 'TC Fire King Art B'],
                           ['5', 'TC Centaur B', 'TC Cleanse Ward P1'],
                           ['6', 'Primal Oni', 'Ammut B']]}},
 'roots': {'spirit': {'cols': ['-ice (Pull Myth From Back)',
                               'Stire (Stagger)'],
                      'discard': ['giant, storm/fire scion',
                                  'caldera, ice scion'],
                      'rows': [['1', 'IC Darkwind', 'Reinforce'],
                               ['2',
                                'Donate Power P2',
                                'Weave Attenuate Life'],
                               ['3',
                                'TC Empower / Pass If Freeze Ray',
                                'Storm King Art B Life'],
                               ['4', '(TC) Woolly / Ray Life', 'TC Empower'],
                               ['5',
                                'TC Empower',
                                'Storm Scion B Life (if 4 blades)'],
                               ['6', '(TC) Donate Power P2', 'TC Furnace'],
                               ['7',
                                '(TC) Donate Power P2',
                                'Ammut B Myth (if 4 traps)'],
                               ['8', 'Dark Surge P2', 'Shadow Shrike'],
                               ['9',
                                'Attenuate Myth',
                                'Fire Scion B Myth (if 3 dots)'],
                               ['10',
                                'Ice Scion B Death (if 4 shields)',
                                'Fire Scion B Death']],
                      'notes': {'1': 'Stall Timer',
                                '3': 'C: Life in Key',
                                '4': 'C: Death in [Life Root Slot]',
                                '6': 'slowly stop stalling',
                                '7': 'C: Myth in Sun',
                                '8': 'If shields stop stalling'},
                      'mana': ['25 Mana', '38 Mana']},
           'ele': {'cols': ['Lyth/Mife (Pull Storm)', 'Steath (Stagger)'],
                   'discard': ['oni, wyldfire, frenzy, death scion',
                               'jinn, owl A, art, myth/life scion'],
                   'rows': [['1', 'Pass', 'TC Empower'],
                            ['2', 'Pass', 'TC Skeletal Dragon B Storm'],
                            ['3', 'Attenuate Fire', 'Pass'],
                            ['4', 'The World B Ice', 'Pass'],
                            ['5', 'TC Empower', 'Frenzy/Reinforce'],
                            ['6',
                             'Life Scion B Fire (if 3 hots)',
                             'TC Storm Owl B Fire'],
                            ['7',
                             'Dark Surge Self',
                             'Death Scion Storm (if 4 weak)'],
                            ['8',
                             'TC Basilisk B Ice',
                             'Dark Surge P1 (WC Death Scion)'],
                            ['9', 'TC Empower', 'Attenuate Ice'],
                            ['10',
                             'Myth Scion B Ice (if 4 traps)',
                             'Death Scion Ice']],
                   'notes': {'1': 'Click Fast',
                             '2': 'C: Storm in Key',
                             '4': 'C: Fire in [Ice Root Slot]',
                             '8': 'C: Ice in Dagger'},
                   'mana': ['35 Mana', '36 Mana']}},
 'decks': {'Ice': {'label': 'Ice (main Ice)',
                   'spells': ['Frost Giant B',
                              'Woolly B',
                              '(IC) Donate Power',
                              'Attenuate',
                              'Dark Surge',
                              'IC Darkwind'],
                   'tc': ['Donate Power',
                          'Donate Power',
                          'Donate Power',
                          'Empower 2x']},
           '-Ice': {'label': '-Ice (off-school Ice)',
                    'spells': ['Donate Power',
                               'Donate Power',
                               '(IC) Donate Power',
                               'Attenuate',
                               'Dark Surge',
                               'IC Darkwind'],
                    'tc': ['Woolly B',
                           'Woolly B',
                           'Frost Giant B',
                           'Empower 2x']},
           'Lyth/Mife': {'label': 'Lyth/Mife',
                         'spells': ['Primal Oni',
                                    'The World B',
                                    'Attenuate',
                                    'Frenzy',
                                    'Dark Surge',
                                    'IC Wyldfire',
                                    'IC Empower'],
                         'tc': ['Centaur B',
                                'Minotaur B',
                                'Basilisk B',
                                'Empower (or Empower x3 if no pet)']},
           'Stire': {'label': 'Stire',
                     'spells': ['Storm King Art B',
                                'Ammut B',
                                'Fire Scion B (can be wc)',
                                'Caldera Jinn',
                                'Reinforce (pet!)',
                                'Weave Attenuate',
                                'Shadow Shrike'],
                     'tc': ['Fire King Art B',
                            'Cleanse Ward',
                            'Empower',
                            'Furnance']},
           'Steath': {'label': 'Steath',
                      'spells': ['Thundering Jinn',
                                 'Storm King Art B',
                                 'Storm Owl A',
                                 'Death Scion B (can be wc)',
                                 'Frenzy/Reinforce',
                                 'Attenuate',
                                 'Dark Surge'],
                      'tc': ['Storm Owl B (main if wc pet)',
                             'Skeletal Dragon B',
                             'Empower']}},
 'deck_notes': [('Woolly B slot',
                 'This can be **Freeze Ray B** — remove 1x Empower TC, and '
                 'pass on Turn 3 in Spirit Roots.'),
                ('Last slot',
                 "You don't need a card here. If you have training points: "
                 '1. Woolly B or Freeze Ray B • 2. Donate Power • 3. Donate '
                 'Power • 4. Donate Power • 5. Attenuate • 6. Dark Surge • '
                 '7. IC Darkwind. TC: 2x Empower (1x if Freeze Ray) + Frost '
                 'Giant B. If Freeze Ray — pass R3 of Roots.'),
                ('Treasure cards',
                 'No need to pack Woolly if you main-deck Freeze Ray B. '
                 'Empower x1 if Freeze Ray.')]}
